spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:          - Path=/api/productos/**
        filters:          - StripPrefix=2
          - name: ExampleGatewayFileFactory
            args: 
              message: Hola mi mensaje personalizado
              cookieName: Usuario
              cookieValue: JakieAlarcon
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
eureka:
    client:
        fetch-registry: true
